---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: order
    app.kubernetes.io/component: service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
      app.kubernetes.io/instance: order
      app.kubernetes.io/component: service
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
        app.kubernetes.io/instance: order
        app.kubernetes.io/component: service
    spec:
      containers:
        - name: order
          image: registry.hochschule-burgenland.muehlbachler.xyz/swm2-ws2025-group-a-order/order:v1.1.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: db_password
            - name: EXTERNAL_SERVICE_NAME_1
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: external_service_name_1
            - name: EXTERNAL_SERVICE_NAME_2
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: external_service_name_2
            - name: EXTERNAL_SERVICE_NAME_3
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: external_service_name_3
            - name: EXTERNAL_SERVICE_URL_1
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: external_service_url_1
            - name: EXTERNAL_SERVICE_URL_2
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: external_service_url_2
            - name: EXTERNAL_SERVICE_URL_3
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: external_service_url_3
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                secretKeyRef:
                  name: order-service-config
                  key: java_tool_options
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: registry-credentials
