---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: order
    app.kubernetes.io/component: service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
      app.kubernetes.io/instance: order
      app.kubernetes.io/component: service
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
        app.kubernetes.io/instance: order
        app.kubernetes.io/component: service
    spec:
      containers:
        - name: order
          image: registry.hochschule-burgenland.muehlbachler.xyz/swm2-ws2025-group-a-order/order:v1.1.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_URL
              value: "jdbc:postgres://group-a-order-orderservice1.b.aivencloud.com:24328/defaultdb?sslmode=require"
            - name: DB_USERNAME
              value: "avnadmin"
            - name: DB_PASSWORD
              value: "AVNS_ONyljJIbjo2ah5Tkses"
            - name: EXTERNAL_SERVICE_NAME_1
              value: "A"
            - name: EXTERNAL_SERVICE_NAME_2
              value: "D"
            - name: EXTERNAL_SERVICE_NAME_3
              value: "E"
            - name: EXTERNAL_SERVICE_URL_1
              value: "inventory.group-a.student.bswe.hochschule-burgenland.muehlbachler.xyz/api/inventory"
            - name: EXTERNAL_SERVICE_URL_2
              value: "inventory.group-d.student.bswe.hochschule-burgenland.muehlbachler.xyz/api/inventory"
            - name: EXTERNAL_SERVICE_URL_3
              value: "inventory.group-e.student.bswe.hochschule-burgenland.muehlbachler.xyz/api/inventory"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=64m -XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=50.0"
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: registry-credentials
